#
# Copyright (c) 2020 Siddharth Chandrasekaran <sidcha.dev@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0
#

name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: configure
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug .
    - name: make
      run: make
    - name: pacakge
      run: |
        make package
        make package_source
        rm -rf ./packages/_CPack_Packages/
        rm -f ./packages/*.tar.bz2
    - uses: actions/upload-artifact@v2
      with:
        name: libosdp-ci-binaries.zip
        path: ./packages/

  BuildLean:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: configure
      run: |
        ./configure
    - name: make
      run: make

  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: configure
      run: cmake .
    - name: make check
      run: make check
